apiVersion: v1
kind: Template
metadata:
  name: product-service-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: product-service:latest
    source:
      contextDir: Product
      git:
        uri: https://github.com/jeremyary/fis2-ecom-services.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis2-mvn-injected-openshift:latest
          namespace: ecom-services
        env:
          - name: MAVEN_ARGS_APPEND
            value: '-B'
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: product-service:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    replicas: 1
    selector:
      app: product-service
      deploymentconfig: product-service
    template:
      metadata:
        labels:
          app: product-service
          deploymentconfig: product-service
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_BROKER_PASSWORD
            value: ${AMQ_PASSWORD}
          - name: ACTIVEMQ_BROKER_USERNAME
            value: ${AMQ_USER}
          - name: ACTIVEMQ_SERVICE_HOST
            value: broker-amq-tcp
          - name: ACTIVEMQ_SERVICE_PORT
            value: "61616"
          imagePullPolicy: IfNotPresent
          name: product-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 9091
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - product-service
        from:
          kind: ImageStreamTag
          name: product-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: product-service
    name: product-service
  spec:
    ports:
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: product-service
      deploymentconfig: product-service
parameters:
  - name: AMQ_USER
    description: A-MQ Username
    value: mquser
  - name: AMQ_PASSWORD
    description: A-MQ password
    value: password
  - name: MONGO_HOST
    description: MongoDB Host
    value: mongodb
  - name: MONGO_PORT
    description: MongoDB Host Port
    value: 27017
  - name: MONGO_DB
    description: MongoDB Collection
    value: ecom
  - name: MONGO_USERNAME
    description: MongoDB Username
    value: mongouser
  - name: MONGO_PASSWORD
    description: MongoDB Password
    value: password