apiVersion: v1
kind: Template
metadata:
  name: sales-service-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: sales-service:latest
    source:
      contextDir: Sales
      git:
        uri: https://github.com/jeremyary/fis2-ecom-services.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: MxjIZoWLfY9ySgCEc5mo
      type: GitHub
    - generic:
        secret: 2Qs5dlAL3FQGSlp5huoa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sales-service:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    replicas: 1
    selector:
      app: sales-service
      deploymentconfig: sales-service
    template:
      metadata:
        labels:
          app: sales-service
          deploymentconfig: sales-service
      spec:
        containers:
        - env:
          - name: ACTIVEMQ_BROKER_PASSWORD
            value: ${AMQ_PASSWORD}
          - name: ACTIVEMQ_BROKER_USERNAME
            value: ${AMQ_USER}
          - name: ACTIVEMQ_SERVICE_HOST
            value: broker-amq-tcp
          - name: ACTIVEMQ_SERVICE_PORT
            value: "61616"
          imagePullPolicy: IfNotPresent
          name: sales-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 9091
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - sales-service
        from:
          kind: ImageStreamTag
          name: sales-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: sales-service
    name: sales-service
  spec:
    ports:
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: sales-service
      deploymentconfig: sales-service
parameters:
  - name: AMQ_USER
    description: A-MQ Username
    value: mquser
  - name: AMQ_PASSWORD
    description: A-MQ password
    value: password